In [1]:
import pandas as pd

In [2]:
print('hi')

hi

In [3]:
dem_election = pd.read_csv('dem_election.csv')
rep_election = pd.read_csv('rep_election.csv')

In [4]:
rep_election.iloc[5]

2026 Partisan Primary\n8/11/2026\nREP Governor - Official Canvass - Finalized On : 8/18/2026 2:43 PM\n100.0% Precincts Reporting (281 of 281)\nGenerated Report on : 9/15/2026 6:12 PM              Precincts
Unnamed: 1                                                                                                                                                                                Tom Tiffany (REP)
Unnamed: 2                                                                                                                                                                                Andy Manske (REP)
Unnamed: 3                                                                                                                                                                                  write-in: (REP)
Name: 5, dtype: object

In [5]:
dem_election

,2026 Partisan Primary\n8/11/2026\nDEM Governor - Official Canvass - Finalized On : 8/18/2026 2:43 PM\n100.0% Precincts Reporting (281 of 281)\nGenerated Report on : 9/15/2026 6:14 PM,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
282,V Shorewood Hills Wds 1-2,440,19,35,255,162,3,12,0
283,V Waunakee 6-16,680,50,67,548,276,2,53,0
284,V Waunakee Wds 1-5,806,71,40,534,242,4,72,0
285,V Windsor Wds 1-5,318,24,32,324,89,3,34,1
286,V Windsor Wds 6-14,454,40,34,389,91,3,45,0

In [6]:
dem_list = list(dem_election.iloc[5])
dem_list

['Precincts',
 'David Crowley (DEM)  ',
 'Sara Rodriguez (DEM)  ',
 'Joel Brennan (DEM)  ',
 'Francesca Hong (DEM)  ',
 'Kelda Roys (DEM)  ',
 'Missy Hughes (DEM)  ',
 'Mandela Barnes (DEM)  ',
 'write-in: (DEM)  ']

In [7]:
list(dem_election.iloc[6])

['C Edgerton Wd 7               ', '8', '2', '1', '5', '0', '0', '0', '0']

In [8]:
dem_data = {}

In [9]:
for x in dem_list:
    dem_data[x] = []
dem_data

{'Precincts': [],
 'David Crowley (DEM)  ': [],
 'Sara Rodriguez (DEM)  ': [],
 'Joel Brennan (DEM)  ': [],
 'Francesca Hong (DEM)  ': [],
 'Kelda Roys (DEM)  ': [],
 'Missy Hughes (DEM)  ': [],
 'Mandela Barnes (DEM)  ': [],
 'write-in: (DEM)  ': []}

In [10]:
for n in range(6, 287):
    listn = list(dem_election.iloc[n])
    for x in range(0, len(listn)):
        dem_data[dem_list[x]].append(listn[x])

In [12]:
dem_df = pd.DataFrame(dem_data)
dem_df

,Precincts,David Crowley (DEM),Sara Rodriguez (DEM),Joel Brennan (DEM),Francesca Hong (DEM),Kelda Roys (DEM),Missy Hughes (DEM),Mandela Barnes (DEM),write-in: (DEM)
0,C Edgerton Wd 7,8,2,1,5,0,0,0,0
1,C Fitchburg Wd 1,131,12,5,194,25,0,6,0
2,C Fitchburg Wd 10,30,7,0,77,3,2,10,1
3,C Fitchburg Wd 11,78,1,3,226,18,0,3,0
4,C Fitchburg Wd 12,211,21,18,429,55,2,15,0
...,...,...,...,...,...,...,...,...,...
276,V Shorewood Hills Wds 1-2,440,19,35,255,162,3,12,0
277,V Waunakee 6-16,680,50,67,548,276,2,53,0
278,V Waunakee Wds 1-5,806,71,40,534,242,4,72,0
279,V Windsor Wds 1-5,318,24,32,324,89,3,34,1
280,V Windsor Wds 6-14,454,40,34,389,91,3,45,0

In [13]:
rep_list = list(rep_election.iloc[5])
rep_data = {}
for x in rep_list:
    rep_data[x] = []
rep_data
for n in range(6, 287):
    listn = list(rep_election.iloc[n])
    for x in range(0, len(listn)):
        rep_data[rep_list[x]].append(listn[x])
rep_df = pd.DataFrame(rep_data)
rep_df

,Precincts,Tom Tiffany (REP),Andy Manske (REP),write-in: (REP)
0,C Edgerton Wd 7,5,0,0
1,C Fitchburg Wd 1,40,3,0
2,C Fitchburg Wd 10,11,2,0
3,C Fitchburg Wd 11,15,2,1
4,C Fitchburg Wd 12,58,1,0
...,...,...,...,...
276,V Shorewood Hills Wds 1-2,32,2,0
277,V Waunakee 6-16,347,25,1
278,V Waunakee Wds 1-5,472,19,1
279,V Windsor Wds 1-5,285,11,0
280,V Windsor Wds 6-14,242,18,0

In [15]:
election_df = pd.merge(dem_df, rep_df, on = "Precincts", how = "inner")
election_df

,Precincts,David Crowley (DEM),Sara Rodriguez (DEM),Joel Brennan (DEM),Francesca Hong (DEM),Kelda Roys (DEM),Missy Hughes (DEM),Mandela Barnes (DEM),write-in: (DEM),Tom Tiffany (REP),Andy Manske (REP),write-in: (REP)
0,C Edgerton Wd 7,8,2,1,5,0,0,0,0,5,0,0
1,C Fitchburg Wd 1,131,12,5,194,25,0,6,0,40,3,0
2,C Fitchburg Wd 10,30,7,0,77,3,2,10,1,11,2,0
3,C Fitchburg Wd 11,78,1,3,226,18,0,3,0,15,2,1
4,C Fitchburg Wd 12,211,21,18,429,55,2,15,0,58,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
276,V Shorewood Hills Wds 1-2,440,19,35,255,162,3,12,0,32,2,0
277,V Waunakee 6-16,680,50,67,548,276,2,53,0,347,25,1
278,V Waunakee Wds 1-5,806,71,40,534,242,4,72,0,472,19,1
279,V Windsor Wds 1-5,318,24,32,324,89,3,34,1,285,11,0
280,V Windsor Wds 6-14,454,40,34,389,91,3,45,0,242,18,0

In [17]:
count = 0
for x in list(election_df['write-in: (DEM)  ']):
    count = count + int(x)
count
0

39